// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1/auth.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AuthEntity) Reset()         { *m = AuthEntity{} }
func (m *AuthEntity) String() string { return proto.CompactTextString(m) }
func (*AuthEntity) ProtoMessage()    {}
func (*AuthEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{0}
}

func (m *AuthEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthEntity.Unmarshal(m, b)
}
func (m *AuthEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthEntity.Marshal(b, m, deterministic)
}
func (m *AuthEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthEntity.Merge(m, src)
}
func (m *AuthEntity) XXX_Size() int {
	return xxx_messageInfo_AuthEntity.Size(m)
}
func (m *AuthEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AuthEntity proto.InternalMessageInfo

func (m *AuthEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AuthEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *AuthEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *AuthEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AuthEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AuthEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AuthEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *AuthEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AuthEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AuthEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *AuthEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AuthEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateAuthReq struct {
	Data                 *AuthEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAuthReq) Reset()         { *m = CreateAuthReq{} }
func (m *CreateAuthReq) String() string { return proto.CompactTextString(m) }
func (*CreateAuthReq) ProtoMessage()    {}
func (*CreateAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{1}
}

func (m *CreateAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthReq.Unmarshal(m, b)
}
func (m *CreateAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthReq.Marshal(b, m, deterministic)
}
func (m *CreateAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthReq.Merge(m, src)
}
func (m *CreateAuthReq) XXX_Size() int {
	return xxx_messageInfo_CreateAuthReq.Size(m)
}
func (m *CreateAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthReq proto.InternalMessageInfo

func (m *CreateAuthReq) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateAuthRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAuthRes) Reset()         { *m = CreateAuthRes{} }
func (m *CreateAuthRes) String() string { return proto.CompactTextString(m) }
func (*CreateAuthRes) ProtoMessage()    {}
func (*CreateAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{2}
}

func (m *CreateAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthRes.Unmarshal(m, b)
}
func (m *CreateAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthRes.Marshal(b, m, deterministic)
}
func (m *CreateAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthRes.Merge(m, src)
}
func (m *CreateAuthRes) XXX_Size() int {
	return xxx_messageInfo_CreateAuthRes.Size(m)
}
func (m *CreateAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthRes proto.InternalMessageInfo

func (m *CreateAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateAuthRes) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAuthReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthReq) Reset()         { *m = GetAuthReq{} }
func (m *GetAuthReq) String() string { return proto.CompactTextString(m) }
func (*GetAuthReq) ProtoMessage()    {}
func (*GetAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{3}
}

func (m *GetAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthReq.Unmarshal(m, b)
}
func (m *GetAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthReq.Marshal(b, m, deterministic)
}
func (m *GetAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthReq.Merge(m, src)
}
func (m *GetAuthReq) XXX_Size() int {
	return xxx_messageInfo_GetAuthReq.Size(m)
}
func (m *GetAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthReq proto.InternalMessageInfo

func (m *GetAuthReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAuthRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAuthRes) Reset()         { *m = GetAuthRes{} }
func (m *GetAuthRes) String() string { return proto.CompactTextString(m) }
func (*GetAuthRes) ProtoMessage()    {}
func (*GetAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{4}
}

func (m *GetAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthRes.Unmarshal(m, b)
}
func (m *GetAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthRes.Marshal(b, m, deterministic)
}
func (m *GetAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthRes.Merge(m, src)
}
func (m *GetAuthRes) XXX_Size() int {
	return xxx_messageInfo_GetAuthRes.Size(m)
}
func (m *GetAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthRes proto.InternalMessageInfo

func (m *GetAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAuthRes) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListAuthReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAuthReq) Reset()         { *m = ListAuthReq{} }
func (m *ListAuthReq) String() string { return proto.CompactTextString(m) }
func (*ListAuthReq) ProtoMessage()    {}
func (*ListAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{5}
}

func (m *ListAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthReq.Unmarshal(m, b)
}
func (m *ListAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthReq.Marshal(b, m, deterministic)
}
func (m *ListAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthReq.Merge(m, src)
}
func (m *ListAuthReq) XXX_Size() int {
	return xxx_messageInfo_ListAuthReq.Size(m)
}
func (m *ListAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthReq proto.InternalMessageInfo

func (m *ListAuthReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAuthReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAuthReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListAuthRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*AuthEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64         `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAuthRes) Reset()         { *m = ListAuthRes{} }
func (m *ListAuthRes) String() string { return proto.CompactTextString(m) }
func (*ListAuthRes) ProtoMessage()    {}
func (*ListAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{6}
}

func (m *ListAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthRes.Unmarshal(m, b)
}
func (m *ListAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthRes.Marshal(b, m, deterministic)
}
func (m *ListAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthRes.Merge(m, src)
}
func (m *ListAuthRes) XXX_Size() int {
	return xxx_messageInfo_ListAuthRes.Size(m)
}
func (m *ListAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthRes proto.InternalMessageInfo

func (m *ListAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListAuthRes) GetData() []*AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListAuthRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateAuthReq struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAuthReq) Reset()         { *m = UpdateAuthReq{} }
func (m *UpdateAuthReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthReq) ProtoMessage()    {}
func (*UpdateAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{7}
}

func (m *UpdateAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthReq.Unmarshal(m, b)
}
func (m *UpdateAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthReq.Marshal(b, m, deterministic)
}
func (m *UpdateAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthReq.Merge(m, src)
}
func (m *UpdateAuthReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthReq.Size(m)
}
func (m *UpdateAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthReq proto.InternalMessageInfo

func (m *UpdateAuthReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAuthReq) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateAuthRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAuthRes) Reset()         { *m = UpdateAuthRes{} }
func (m *UpdateAuthRes) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthRes) ProtoMessage()    {}
func (*UpdateAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{8}
}

func (m *UpdateAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthRes.Unmarshal(m, b)
}
func (m *UpdateAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthRes.Marshal(b, m, deterministic)
}
func (m *UpdateAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthRes.Merge(m, src)
}
func (m *UpdateAuthRes) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthRes.Size(m)
}
func (m *UpdateAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthRes proto.InternalMessageInfo

func (m *UpdateAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateAuthRes) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteAuthReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthReq) Reset()         { *m = DeleteAuthReq{} }
func (m *DeleteAuthReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthReq) ProtoMessage()    {}
func (*DeleteAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{9}
}

func (m *DeleteAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthReq.Unmarshal(m, b)
}
func (m *DeleteAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthReq.Marshal(b, m, deterministic)
}
func (m *DeleteAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthReq.Merge(m, src)
}
func (m *DeleteAuthReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthReq.Size(m)
}
func (m *DeleteAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthReq proto.InternalMessageInfo

func (m *DeleteAuthReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAuthRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthRes) Reset()         { *m = DeleteAuthRes{} }
func (m *DeleteAuthRes) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthRes) ProtoMessage()    {}
func (*DeleteAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{10}
}

func (m *DeleteAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthRes.Unmarshal(m, b)
}
func (m *DeleteAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthRes.Marshal(b, m, deterministic)
}
func (m *DeleteAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthRes.Merge(m, src)
}
func (m *DeleteAuthRes) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthRes.Size(m)
}
func (m *DeleteAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthRes proto.InternalMessageInfo

func (m *DeleteAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthEntity)(nil), "auth.v1.AuthEntity")
	proto.RegisterMapType((map[string]string)(nil), "auth.v1.AuthEntity.MetadataEntry")
	proto.RegisterType((*CreateAuthReq)(nil), "auth.v1.CreateAuthReq")
	proto.RegisterType((*CreateAuthRes)(nil), "auth.v1.CreateAuthRes")
	proto.RegisterType((*GetAuthReq)(nil), "auth.v1.GetAuthReq")
	proto.RegisterType((*GetAuthRes)(nil), "auth.v1.GetAuthRes")
	proto.RegisterType((*ListAuthReq)(nil), "auth.v1.ListAuthReq")
	proto.RegisterType((*ListAuthRes)(nil), "auth.v1.ListAuthRes")
	proto.RegisterType((*UpdateAuthReq)(nil), "auth.v1.UpdateAuthReq")
	proto.RegisterType((*UpdateAuthRes)(nil), "auth.v1.UpdateAuthRes")
	proto.RegisterType((*DeleteAuthReq)(nil), "auth.v1.DeleteAuthReq")
	proto.RegisterType((*DeleteAuthRes)(nil), "auth.v1.DeleteAuthRes")
}

func init() {
	proto.RegisterFile("auth/v1/auth.proto", fileDescriptor_24d92db81f25f2da)
}

var fileDescriptor_24d92db81f25f2da = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xe3, 0xa4, 0x49, 0x27, 0x4d, 0x75, 0xba, 0xad, 0x7a, 0x7c, 0xac, 0x1e, 0xd5, 0xf8,
	0x06, 0xab, 0x52, 0x6d, 0x5a, 0x6e, 0x4a, 0x11, 0x17, 0x69, 0xa9, 0xe0, 0xa2, 0x50, 0xc9, 0xa5,
	0x42, 0xea, 0x0d, 0xda, 0xd8, 0x4b, 0xb2, 0x6a, 0x1c, 0x07, 0xef, 0x3a, 0x52, 0x84, 0x90, 0x10,
	0xaf, 0xc0, 0x1b, 0xf0, 0x12, 0x3c, 0x08, 0xaf, 0xc0, 0x83, 0xa0, 0x5d, 0xaf, 0xff, 0x68, 0x4a,
	0x11, 0xa8, 0x57, 0xd9, 0x99, 0x9d, 0x6f, 0xfc, 0xcd, 0xcc, 0x37, 0x1b, 0x40, 0x38, 0xe5, 0x23,
	0x6f, 0xb6, 0xe7, 0x89, 0x5f, 0x77, 0x9a, 0xc4, 0x3c, 0x46, 0x6d, 0x79, 0x9e, 0xed, 0x99, 0xdb,
	0xc3, 0x38, 0x1e, 0x8e, 0x89, 0x27, 0xdd, 0x83, 0xf4, 0xad, 0xc7, 0x69, 0x44, 0x18, 0xc7, 0xd1,
	0x34, 0x8b, 0x34, 0xb7, 0x54, 0x00, 0x9e, 0x52, 0x0f, 0x4f, 0x26, 0x31, 0xc7, 0x9c, 0xc6, 0x13,
	0x96, 0xdd, 0xda, 0x5f, 0x9a, 0x00, 0xfd, 0x94, 0x8f, 0x4e, 0x26, 0x9c, 0xf2, 0x39, 0x5a, 0x85,
	0x06, 0x0d, 0x0d, 0xcd, 0xd2, 0x9c, 0x65, 0xbf, 0x41, 0x43, 0x84, 0xa0, 0x39, 0xc1, 0x11, 0x31,
	0x1a, 0xd2, 0x23, 0xcf, 0xc8, 0x82, 0x6e, 0x48, 0x58, 0x90, 0xd0, 0xa9, 0x48, 0x64, 0xe8, 0xf2,
	0xaa, 0xea, 0x42, 0x9b, 0xb0, 0xc4, 0x38, 0xe6, 0x29, 0x33, 0x9a, 0x96, 0xe6, 0x74, 0x7c, 0x65,
	0xa1, 0x7f, 0x40, 0xc7, 0x43, 0x62, 0xb4, 0x2c, 0xcd, 0x69, 0xf9, 0xe2, 0x88, 0x36, 0xa0, 0xc5,
	0x63, 0x8e, 0xc7, 0xc6, 0x92, 0xa5, 0x39, 0xba, 0x9f, 0x19, 0xc2, 0x3b, 0x4d, 0x68, 0x40, 0x8c,
	0xb6, 0xa5, 0x39, 0x9a, 0x9f, 0x19, 0x82, 0x0b, 0xc7, 0x43, 0x66, 0x74, 0x2c, 0x5d, 0x70, 0x11,
	0x67, 0x64, 0x40, 0x7b, 0x92, 0x46, 0x03, 0x92, 0x30, 0x63, 0xd9, 0xd2, 0x9d, 0x96, 0x9f, 0x9b,
	0xe8, 0x09, 0x74, 0x22, 0xc2, 0x71, 0x88, 0x39, 0x36, 0xc0, 0xd2, 0x9d, 0xee, 0xfe, 0x3d, 0x57,
	0xf5, 0xcc, 0x2d, 0x0b, 0x76, 0x5f, 0xa8, 0x98, 0x93, 0x09, 0x4f, 0xe6, 0x7e, 0x01, 0x41, 0xff,
	0x03, 0x04, 0x09, 0xc1, 0x9c, 0x84, 0x6f, 0x06, 0x73, 0xa3, 0x2b, 0x6b, 0x5c, 0x56, 0x9e, 0xa3,
	0x39, 0x7a, 0x54, 0x5e, 0x63, 0x6e, 0xac, 0x58, 0x9a, 0xd3, 0xdd, 0x37, 0xdd, 0xac, 0xd3, 0x6e,
	0x3e, 0x0a, 0xf7, 0x55, 0x3e, 0x8a, 0x02, 0xda, 0xe7, 0x02, 0x9a, 0x4e, 0xc3, 0x1c, 0xda, 0xbb,
	0x1d, 0xaa, 0xa2, 0x33, 0x68, 0x48, 0xc6, 0x44, 0x41, 0x57, 0x6f, 0x87, 0xaa, 0xe8, 0x3e, 0x37,
	0x1f, 0x43, 0xaf, 0x56, 0xaa, 0x98, 0xc5, 0x15, 0x99, 0xab, 0x51, 0x8b, 0xa3, 0xe8, 0xfa, 0x0c,
	0x8f, 0xd3, 0x7c, 0xd8, 0x99, 0x71, 0xd8, 0x38, 0xd0, 0xec, 0x03, 0xe8, 0x1d, 0x4b, 0xfe, 0xa2,
	0x71, 0x3e, 0x79, 0x87, 0xee, 0x43, 0x53, 0x36, 0x56, 0x93, 0x14, 0xd6, 0x17, 0x34, 0xd6, 0x97,
	0x01, 0xf6, 0xb8, 0x8e, 0x94, 0x03, 0x63, 0x69, 0x10, 0x10, 0xc6, 0x24, 0xb8, 0xe3, 0xe7, 0xa6,
	0xb8, 0x89, 0x08, 0x63, 0x42, 0x20, 0x19, 0x81, 0xdc, 0x2c, 0xbe, 0xa6, 0xdf, 0xf6, 0xb5, 0x2d,
	0x80, 0x67, 0x84, 0xe7, 0x24, 0x7f, 0xd2, 0xb2, 0x4d, 0x2b, 0xb7, 0x77, 0x4c, 0xe4, 0x0c, 0xba,
	0xa7, 0x94, 0x15, 0x4c, 0x10, 0x34, 0xa7, 0x22, 0x9d, 0x26, 0x85, 0x2f, 0xcf, 0xa2, 0xdb, 0x63,
	0x1a, 0x51, 0x2e, 0xbf, 0xd1, 0xf2, 0x33, 0x43, 0x6e, 0x0e, 0xc1, 0x49, 0x30, 0x52, 0x6b, 0xa5,
	0x2c, 0xfb, 0xa3, 0x56, 0xcd, 0xf8, 0xb7, 0xec, 0xf5, 0x5f, 0xb2, 0x2f, 0x97, 0xb2, 0x59, 0x59,
	0x4a, 0xfb, 0x39, 0xf4, 0x2e, 0xa4, 0x12, 0x6f, 0xe8, 0x6f, 0x91, 0xbf, 0xf1, 0x1b, 0xa2, 0xa8,
	0x66, 0xba, 0xe3, 0x59, 0x6c, 0x43, 0xef, 0xa9, 0x5c, 0x83, 0x9b, 0x74, 0x71, 0x5c, 0x0f, 0xf8,
	0x23, 0x3a, 0xfb, 0x5f, 0x75, 0xe8, 0x0a, 0xfc, 0x39, 0x49, 0x66, 0xe2, 0xb1, 0xba, 0x00, 0x28,
	0x85, 0x8f, 0x36, 0x0b, 0x7a, 0xb5, 0x3d, 0x32, 0x17, 0xfb, 0x99, 0xfd, 0xef, 0xa7, 0x6f, 0xdf,
	0x3f, 0x37, 0xd6, 0xec, 0x15, 0xf9, 0x6a, 0xab, 0x97, 0xff, 0x50, 0xdb, 0x41, 0x2f, 0xa1, 0xad,
	0x34, 0x8c, 0xca, 0x92, 0x4b, 0xcd, 0x9b, 0x0b, 0x9c, 0xcc, 0xfe, 0x4f, 0x66, 0x5b, 0x47, 0x6b,
	0xd5, 0x6c, 0xde, 0x7b, 0x1a, 0x7e, 0x40, 0xa7, 0xd0, 0xc9, 0x65, 0x85, 0x36, 0x0a, 0x6c, 0x45,
	0xbb, 0xe6, 0x22, 0x2f, 0xb3, 0x37, 0x64, 0xca, 0x55, 0x54, 0x23, 0x88, 0x2e, 0x01, 0xca, 0xc1,
	0x56, 0x8a, 0xae, 0xe9, 0xc6, 0x5c, 0xec, 0x67, 0xf6, 0x96, 0xcc, 0xb9, 0x69, 0x5e, 0xa7, 0x29,
	0x2a, 0x7f, 0x0d, 0x50, 0x4e, 0xa9, 0x92, 0xbb, 0x36, 0x5b, 0x73, 0xb1, 0xbf, 0x68, 0xc1, 0xce,
	0xf5, 0xdc, 0x47, 0x0f, 0x2e, 0xdd, 0x21, 0xe5, 0xa3, 0x74, 0xe0, 0x06, 0x71, 0xe4, 0x9d, 0x9d,
	0x1f, 0xf7, 0x7d, 0xc6, 0x71, 0x70, 0x95, 0x7a, 0x6c, 0x84, 0x13, 0x12, 0xee, 0x0e, 0xe3, 0x5d,
	0xf9, 0xb6, 0x7a, 0xea, 0x6f, 0x78, 0xb0, 0x24, 0xcd, 0x87, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0x20, 0x2c, 0x64, 0x98, 0x07, 0x00, 0x00,
}
