syntax = "proto3";

package admin.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/OSCARstacku/shared-go-proto/admin/v1";

// -------------------------------------------------------------------
// Admin Entity message
// -------------------------------------------------------------------

message AdminEntity {
  string id = 1;
  string name = 2;
  string description = 3;
  bool status = 4;
  int32 age = 5;
  int64 total = 6;
  double price = 7;
  repeated string tags = 8;
  repeated int32 numbers = 9;
  map<string, string> metadata = 10;

  string created_by = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  google.protobuf.Timestamp deleted_at = 14;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreateBase
// -------------------------------------------------------------------

message CreateAdminReq {
  AdminEntity data = 1;
}

message CreateAdminRes {
  bool success = 1;
  string message = 2;
  AdminEntity data = 3;
}

// -------------------------------------------------------------------
// GetBase
// -------------------------------------------------------------------

message GetAdminReq {
  string id = 1;
}

message GetAdminRes {
  bool success = 1;
  string message = 2;
  AdminEntity data = 3;
}

// -------------------------------------------------------------------
// ListBase
// -------------------------------------------------------------------

message ListAdminReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListAdminRes {
  bool success = 1;
  string message = 2;
  repeated AdminEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdateBase
// -------------------------------------------------------------------

message UpdateAdminReq {
  string id = 1;
  AdminEntity data = 2;
}

message UpdateAdminRes {
  bool success = 1;
  string message = 2;
  AdminEntity data = 3;
}

// -------------------------------------------------------------------
// DeleteBase
// -------------------------------------------------------------------

message DeleteAdminReq {
  string id = 1;
}

message DeleteAdminRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service AdminService {

  rpc CreateAdmin(CreateAdminReq) returns (CreateAdminRes) {
    option (google.api.http) = {
      post: "/api/v1/admin"
      body: "*"
    };
  }

  rpc GetAdmin(GetAdminReq) returns (GetAdminRes) {
    option (google.api.http) = {
      get: "/api/v1/admin/{id}"
    };
  }

  rpc ListAdmin(ListAdminReq) returns (ListAdminRes) {
    option (google.api.http) = {
      get: "/api/v1/admin"
    };
  }

  rpc UpdateAdmin(UpdateAdminReq) returns (UpdateAdminRes) {
    option (google.api.http) = {
      put: "/api/v1/admin/{id}"
      body: "*"
    };
  }

  rpc DeleteAdmin(DeleteAdminReq) returns (DeleteAdminRes) {
    option (google.api.http) = {
      delete: "/api/v1/admin/{id}"
    };
  }

}
