// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/v1/base.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseEntity struct {
	XId                  string                 `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BaseEntity) Reset()         { *m = BaseEntity{} }
func (m *BaseEntity) String() string { return proto.CompactTextString(m) }
func (*BaseEntity) ProtoMessage()    {}
func (*BaseEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{0}
}

func (m *BaseEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseEntity.Unmarshal(m, b)
}
func (m *BaseEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseEntity.Marshal(b, m, deterministic)
}
func (m *BaseEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseEntity.Merge(m, src)
}
func (m *BaseEntity) XXX_Size() int {
	return xxx_messageInfo_BaseEntity.Size(m)
}
func (m *BaseEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BaseEntity proto.InternalMessageInfo

func (m *BaseEntity) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *BaseEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BaseEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *BaseEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *BaseEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BaseEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BaseEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BaseEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *BaseEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BaseEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *BaseEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *BaseEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *BaseEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

// CreateBase
type CreateBaseReq struct {
	Data                 *BaseEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateBaseReq) Reset()         { *m = CreateBaseReq{} }
func (m *CreateBaseReq) String() string { return proto.CompactTextString(m) }
func (*CreateBaseReq) ProtoMessage()    {}
func (*CreateBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{1}
}

func (m *CreateBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBaseReq.Unmarshal(m, b)
}
func (m *CreateBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBaseReq.Marshal(b, m, deterministic)
}
func (m *CreateBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBaseReq.Merge(m, src)
}
func (m *CreateBaseReq) XXX_Size() int {
	return xxx_messageInfo_CreateBaseReq.Size(m)
}
func (m *CreateBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBaseReq proto.InternalMessageInfo

func (m *CreateBaseReq) GetData() *BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateBaseRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BaseEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateBaseRes) Reset()         { *m = CreateBaseRes{} }
func (m *CreateBaseRes) String() string { return proto.CompactTextString(m) }
func (*CreateBaseRes) ProtoMessage()    {}
func (*CreateBaseRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{2}
}

func (m *CreateBaseRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBaseRes.Unmarshal(m, b)
}
func (m *CreateBaseRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBaseRes.Marshal(b, m, deterministic)
}
func (m *CreateBaseRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBaseRes.Merge(m, src)
}
func (m *CreateBaseRes) XXX_Size() int {
	return xxx_messageInfo_CreateBaseRes.Size(m)
}
func (m *CreateBaseRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBaseRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBaseRes proto.InternalMessageInfo

func (m *CreateBaseRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateBaseRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateBaseRes) GetData() *BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

// GetBase
type GetBaseReq struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBaseReq) Reset()         { *m = GetBaseReq{} }
func (m *GetBaseReq) String() string { return proto.CompactTextString(m) }
func (*GetBaseReq) ProtoMessage()    {}
func (*GetBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{3}
}

func (m *GetBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBaseReq.Unmarshal(m, b)
}
func (m *GetBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBaseReq.Marshal(b, m, deterministic)
}
func (m *GetBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBaseReq.Merge(m, src)
}
func (m *GetBaseReq) XXX_Size() int {
	return xxx_messageInfo_GetBaseReq.Size(m)
}
func (m *GetBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBaseReq proto.InternalMessageInfo

func (m *GetBaseReq) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type GetBaseRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BaseEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBaseRes) Reset()         { *m = GetBaseRes{} }
func (m *GetBaseRes) String() string { return proto.CompactTextString(m) }
func (*GetBaseRes) ProtoMessage()    {}
func (*GetBaseRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{4}
}

func (m *GetBaseRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBaseRes.Unmarshal(m, b)
}
func (m *GetBaseRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBaseRes.Marshal(b, m, deterministic)
}
func (m *GetBaseRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBaseRes.Merge(m, src)
}
func (m *GetBaseRes) XXX_Size() int {
	return xxx_messageInfo_GetBaseRes.Size(m)
}
func (m *GetBaseRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBaseRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetBaseRes proto.InternalMessageInfo

func (m *GetBaseRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetBaseRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetBaseRes) GetData() *BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

// ListBase
type ListBaseReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBaseReq) Reset()         { *m = ListBaseReq{} }
func (m *ListBaseReq) String() string { return proto.CompactTextString(m) }
func (*ListBaseReq) ProtoMessage()    {}
func (*ListBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{5}
}

func (m *ListBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBaseReq.Unmarshal(m, b)
}
func (m *ListBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBaseReq.Marshal(b, m, deterministic)
}
func (m *ListBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBaseReq.Merge(m, src)
}
func (m *ListBaseReq) XXX_Size() int {
	return xxx_messageInfo_ListBaseReq.Size(m)
}
func (m *ListBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListBaseReq proto.InternalMessageInfo

func (m *ListBaseReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListBaseReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListBaseReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListBaseRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*BaseEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64         `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBaseRes) Reset()         { *m = ListBaseRes{} }
func (m *ListBaseRes) String() string { return proto.CompactTextString(m) }
func (*ListBaseRes) ProtoMessage()    {}
func (*ListBaseRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{6}
}

func (m *ListBaseRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBaseRes.Unmarshal(m, b)
}
func (m *ListBaseRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBaseRes.Marshal(b, m, deterministic)
}
func (m *ListBaseRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBaseRes.Merge(m, src)
}
func (m *ListBaseRes) XXX_Size() int {
	return xxx_messageInfo_ListBaseRes.Size(m)
}
func (m *ListBaseRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBaseRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListBaseRes proto.InternalMessageInfo

func (m *ListBaseRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListBaseRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListBaseRes) GetData() []*BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListBaseRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// UpdateBase
type UpdateBaseReq struct {
	XId                  string      `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Data                 *BaseEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateBaseReq) Reset()         { *m = UpdateBaseReq{} }
func (m *UpdateBaseReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBaseReq) ProtoMessage()    {}
func (*UpdateBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{7}
}

func (m *UpdateBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBaseReq.Unmarshal(m, b)
}
func (m *UpdateBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBaseReq.Marshal(b, m, deterministic)
}
func (m *UpdateBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBaseReq.Merge(m, src)
}
func (m *UpdateBaseReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBaseReq.Size(m)
}
func (m *UpdateBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBaseReq proto.InternalMessageInfo

func (m *UpdateBaseReq) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *UpdateBaseReq) GetData() *BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateBaseRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BaseEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateBaseRes) Reset()         { *m = UpdateBaseRes{} }
func (m *UpdateBaseRes) String() string { return proto.CompactTextString(m) }
func (*UpdateBaseRes) ProtoMessage()    {}
func (*UpdateBaseRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{8}
}

func (m *UpdateBaseRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBaseRes.Unmarshal(m, b)
}
func (m *UpdateBaseRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBaseRes.Marshal(b, m, deterministic)
}
func (m *UpdateBaseRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBaseRes.Merge(m, src)
}
func (m *UpdateBaseRes) XXX_Size() int {
	return xxx_messageInfo_UpdateBaseRes.Size(m)
}
func (m *UpdateBaseRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBaseRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBaseRes proto.InternalMessageInfo

func (m *UpdateBaseRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateBaseRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateBaseRes) GetData() *BaseEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

// DeleteBase
type DeleteBaseReq struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBaseReq) Reset()         { *m = DeleteBaseReq{} }
func (m *DeleteBaseReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBaseReq) ProtoMessage()    {}
func (*DeleteBaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{9}
}

func (m *DeleteBaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBaseReq.Unmarshal(m, b)
}
func (m *DeleteBaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBaseReq.Marshal(b, m, deterministic)
}
func (m *DeleteBaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBaseReq.Merge(m, src)
}
func (m *DeleteBaseReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBaseReq.Size(m)
}
func (m *DeleteBaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBaseReq proto.InternalMessageInfo

func (m *DeleteBaseReq) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type DeleteBaseRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBaseRes) Reset()         { *m = DeleteBaseRes{} }
func (m *DeleteBaseRes) String() string { return proto.CompactTextString(m) }
func (*DeleteBaseRes) ProtoMessage()    {}
func (*DeleteBaseRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_609c3acb0f815e11, []int{10}
}

func (m *DeleteBaseRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBaseRes.Unmarshal(m, b)
}
func (m *DeleteBaseRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBaseRes.Marshal(b, m, deterministic)
}
func (m *DeleteBaseRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBaseRes.Merge(m, src)
}
func (m *DeleteBaseRes) XXX_Size() int {
	return xxx_messageInfo_DeleteBaseRes.Size(m)
}
func (m *DeleteBaseRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBaseRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBaseRes proto.InternalMessageInfo

func (m *DeleteBaseRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteBaseRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseEntity)(nil), "base.v1.BaseEntity")
	proto.RegisterMapType((map[string]string)(nil), "base.v1.BaseEntity.MetadataEntry")
	proto.RegisterType((*CreateBaseReq)(nil), "base.v1.CreateBaseReq")
	proto.RegisterType((*CreateBaseRes)(nil), "base.v1.CreateBaseRes")
	proto.RegisterType((*GetBaseReq)(nil), "base.v1.GetBaseReq")
	proto.RegisterType((*GetBaseRes)(nil), "base.v1.GetBaseRes")
	proto.RegisterType((*ListBaseReq)(nil), "base.v1.ListBaseReq")
	proto.RegisterType((*ListBaseRes)(nil), "base.v1.ListBaseRes")
	proto.RegisterType((*UpdateBaseReq)(nil), "base.v1.UpdateBaseReq")
	proto.RegisterType((*UpdateBaseRes)(nil), "base.v1.UpdateBaseRes")
	proto.RegisterType((*DeleteBaseReq)(nil), "base.v1.DeleteBaseReq")
	proto.RegisterType((*DeleteBaseRes)(nil), "base.v1.DeleteBaseRes")
}

func init() {
	proto.RegisterFile("base/v1/base.proto", fileDescriptor_609c3acb0f815e11)
}

var fileDescriptor_609c3acb0f815e11 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x95, 0x9b, 0x76, 0xed, 0x6e, 0x7f, 0xfd, 0x81, 0xcc, 0x34, 0x59, 0x91, 0x26, 0x42, 0x5f,
	0xc8, 0xcb, 0x12, 0xb6, 0x49, 0x68, 0xfc, 0x7b, 0xd8, 0xc6, 0x84, 0x26, 0x81, 0x26, 0x79, 0xf0,
	0xc2, 0xcb, 0xe4, 0x26, 0xa6, 0x8b, 0xd6, 0x34, 0x21, 0x76, 0x2a, 0xf5, 0x8d, 0xef, 0xc2, 0x57,
	0xe0, 0x03, 0x22, 0x3b, 0xce, 0x3f, 0x94, 0x51, 0x04, 0xda, 0x53, 0x7d, 0xaf, 0xef, 0xb1, 0x8f,
	0xcf, 0x3d, 0x37, 0x05, 0x3c, 0x63, 0x82, 0xfb, 0xab, 0x03, 0x5f, 0xfd, 0x7a, 0x69, 0x96, 0xc8,
	0x04, 0x0f, 0xf5, 0x7a, 0x75, 0x60, 0x3f, 0x9e, 0x27, 0xc9, 0x7c, 0xc1, 0x7d, 0x9d, 0x9e, 0xe5,
	0x5f, 0x7c, 0x19, 0xc5, 0x5c, 0x48, 0x16, 0xa7, 0x45, 0xe5, 0xf4, 0x7b, 0x1f, 0xe0, 0x94, 0x09,
	0x7e, 0xbe, 0x94, 0x91, 0x5c, 0xe3, 0x07, 0x60, 0x5d, 0x47, 0x21, 0x41, 0x0e, 0x72, 0xb7, 0x69,
	0xef, 0x22, 0xc4, 0x18, 0xfa, 0x4b, 0x16, 0x73, 0xd2, 0xd3, 0x19, 0xbd, 0xc6, 0x0e, 0x8c, 0x43,
	0x2e, 0x82, 0x2c, 0x4a, 0x65, 0x94, 0x2c, 0x89, 0xa5, 0xb7, 0x9a, 0x29, 0xbc, 0x0b, 0x5b, 0x42,
	0x32, 0x99, 0x0b, 0xd2, 0x77, 0x90, 0x3b, 0xa2, 0x26, 0xc2, 0x0f, 0xc1, 0x62, 0x73, 0x4e, 0x06,
	0x0e, 0x72, 0x07, 0x54, 0x2d, 0xf1, 0x0e, 0x0c, 0x64, 0x22, 0xd9, 0x82, 0x6c, 0x39, 0xc8, 0xb5,
	0x68, 0x11, 0xa8, 0x6c, 0x9a, 0x45, 0x01, 0x27, 0x43, 0x07, 0xb9, 0x88, 0x16, 0x81, 0xe2, 0x22,
	0xd9, 0x5c, 0x90, 0x91, 0x63, 0x29, 0x2e, 0x6a, 0x8d, 0x09, 0x0c, 0x97, 0x79, 0x3c, 0xe3, 0x99,
	0x20, 0xdb, 0x8e, 0xe5, 0x0e, 0x68, 0x19, 0xe2, 0x37, 0x30, 0x8a, 0xb9, 0x64, 0x21, 0x93, 0x8c,
	0x80, 0x63, 0xb9, 0xe3, 0xc3, 0x27, 0x9e, 0x91, 0xc5, 0xab, 0x5f, 0xec, 0x7d, 0x30, 0x35, 0xe7,
	0x4b, 0x99, 0xad, 0x69, 0x05, 0xc1, 0x7b, 0x00, 0x41, 0xc6, 0x99, 0xe4, 0xe1, 0xf5, 0x6c, 0x4d,
	0xc6, 0xfa, 0x8d, 0xdb, 0x26, 0x73, 0xba, 0xc6, 0x2f, 0xea, 0x6d, 0x26, 0xc9, 0x7f, 0x0e, 0x72,
	0xc7, 0x87, 0xb6, 0x57, 0xa8, 0xed, 0x95, 0x6a, 0x7b, 0x1f, 0x4b, 0xb5, 0x2b, 0xe8, 0x89, 0x54,
	0xd0, 0x3c, 0x0d, 0x4b, 0xe8, 0x64, 0x33, 0xd4, 0x54, 0x17, 0xd0, 0x90, 0x2f, 0xb8, 0x81, 0xfe,
	0xbf, 0x19, 0x6a, 0xaa, 0x4f, 0xa4, 0xfd, 0x0a, 0x26, 0xad, 0xa7, 0xaa, 0x5e, 0xdc, 0xf2, 0xb5,
	0x69, 0xb5, 0x5a, 0x2a, 0xd5, 0x57, 0x6c, 0x91, 0x97, 0xcd, 0x2e, 0x82, 0x97, 0xbd, 0x63, 0x34,
	0x3d, 0x86, 0xc9, 0x99, 0xe6, 0xaf, 0x84, 0xa3, 0xfc, 0x2b, 0x7e, 0x0a, 0x7d, 0x2d, 0x2c, 0xd2,
	0x14, 0x1e, 0x75, 0x08, 0x4b, 0x75, 0xc1, 0x74, 0xd1, 0x46, 0xea, 0x86, 0x89, 0x3c, 0x08, 0xb8,
	0x10, 0x1a, 0x3c, 0xa2, 0x65, 0xa8, 0x76, 0x62, 0x2e, 0x84, 0x32, 0x48, 0x41, 0xa0, 0x0c, 0xab,
	0xdb, 0xac, 0x4d, 0xb7, 0xed, 0x01, 0xbc, 0xe3, 0xb2, 0x24, 0xf9, 0xab, 0x99, 0xa7, 0x51, 0x63,
	0xfb, 0x9e, 0x99, 0x5c, 0xc2, 0xf8, 0x7d, 0x24, 0x2a, 0x2a, 0x18, 0xfa, 0xa9, 0x3a, 0x0e, 0x69,
	0xe7, 0xeb, 0xb5, 0x92, 0x7b, 0x11, 0xc5, 0x91, 0xd4, 0x77, 0x0c, 0x68, 0x11, 0xe8, 0xd1, 0xe1,
	0x2c, 0x0b, 0x6e, 0xcc, 0x5c, 0x99, 0x68, 0xfa, 0x0d, 0x35, 0x4f, 0xfc, 0x57, 0xf6, 0xd6, 0x6f,
	0xd9, 0xd7, 0x53, 0xd9, 0x6f, 0x4c, 0xe5, 0xf4, 0x02, 0x26, 0x9f, 0xb4, 0x15, 0xef, 0x12, 0xb8,
	0xba, 0xa0, 0xf7, 0x07, 0xb6, 0x68, 0x1e, 0x75, 0xcf, 0xcd, 0x70, 0x60, 0xf2, 0x56, 0x0f, 0xc2,
	0x9d, 0xce, 0x38, 0x6b, 0x57, 0xfc, 0x15, 0x9f, 0xc3, 0x1f, 0x3d, 0x18, 0x2b, 0xfc, 0x15, 0xcf,
	0x56, 0xea, 0x7b, 0xf5, 0x1a, 0xa0, 0xf6, 0x3e, 0xde, 0xad, 0xf8, 0xb5, 0x46, 0xc9, 0xee, 0xce,
	0x0b, 0x7c, 0x04, 0x43, 0x63, 0x56, 0x5c, 0x3f, 0xad, 0x76, 0xb7, 0xdd, 0x91, 0x14, 0xf8, 0x39,
	0x8c, 0x4a, 0x93, 0xe0, 0x9d, 0xaa, 0xa0, 0xe1, 0x44, 0xbb, 0x2b, 0x2b, 0x14, 0xd5, 0xba, 0x1f,
	0x0d, 0xaa, 0xad, 0x7e, 0xdb, 0xdd, 0x79, 0x8d, 0xae, 0xd5, 0x6b, 0xa0, 0x5b, 0xa2, 0xdb, 0xdd,
	0x79, 0x71, 0xfa, 0xec, 0xb3, 0x37, 0x8f, 0xe4, 0x4d, 0x3e, 0xf3, 0x82, 0x24, 0xf6, 0x2f, 0xaf,
	0xce, 0x4e, 0xa8, 0x90, 0x2c, 0xb8, 0xcd, 0x7d, 0x71, 0xc3, 0x32, 0x1e, 0xee, 0xcf, 0x93, 0x7d,
	0xfd, 0x6d, 0xf3, 0xcd, 0x3f, 0xdd, 0x6c, 0x4b, 0x87, 0x47, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x04, 0x21, 0x5c, 0x5f, 0xfb, 0x06, 0x00, 0x00,
}
